---
- name: Install build packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ build_packages }}"

- name: Install base packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- name: Add primary user
  user:
    name: "{{ primary_user }}"
    groups: "{{ primary_user }}"

- name: Add vim autoload directory
  file:
    name: ~/.vim/autoload
    state: directory
  become: true
  become_user: "{{ primary_user }}"

- name: Install .vimrc
  get_url:
    url: https://raw.githubusercontent.com/nerdsvilleceo/.files/master/.vimrc
    dest: "~/.vimrc"
  become: true
  become_user: "{{ primary_user }}"

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.vim/autoload/plug.vim"
  become: true
  become_user: "{{ primary_user }}"

- name: Install vim-plug plugins
  command: vim +PlugInstall +qall  # noqa 301
  become: true
  become_user: "{{ primary_user }}"

- name: Remove build packages
  package:
    name: "{{ item }}"
    state: removed 
  with_items: "{{ build_packages }}"
