---
- name: Set packages minus removed ones
  set_fact:
    packages: "{{ packages | difference(remove_packages) }}"
- include_tasks: users.yml
- include_tasks: dependencies_{{ ansible_os_family | lower }}.yml
- include_tasks: services.yml
- include_tasks: golang.yml
- include_tasks: git.yml
